using System;
using Il2CppInterop.Runtime.InteropTypes.Arrays;
using UnityEngine;

namespace KingdomAccess.Speech;

/// <summary>
/// Sounds played through the game's own audio engine, with volume and stereo position (unlike
/// the WAV alerts played by Windows). The sounds are generated by the mod: a heartbeat used as a
/// guiding beacon, and a short chime meaning "you can pay here".
/// </summary>
internal static class GameAudio
{
    private const int Rate = 44100;
    private static GameObject _host;
    private static AudioSource _source;
    /// <summary>
    /// Several sources: the stereo position applies to everything a source plays, so each
    /// overlapping sound needs its own source to keep its side.
    /// </summary>
    private static AudioSource[] _pool;
    private static int _next;
    private static AudioClip _heartbeat, _chime;
    public static bool Enabled = true;
    internal static IModLog Log;
    private static bool _selfTestDone;

    /// <summary>
    /// Diagnostics, once: plays an almost silent sound and logs what Unity reports (listener,
    /// global volume, clip, whether the source really plays).
    /// </summary>
    public static void SelfTest()
    {
        if (_selfTestDone) return;
        _selfTestDone = true;
        try
        {
            var listeners = UnityEngine.Object.FindObjectsByType<AudioListener>(FindObjectsSortMode.None);
            int active = 0;
            foreach (var l in listeners) if (l != null && l.isActiveAndEnabled) active++;
            bool ok = Ensure();
            var clip = _chime;
            string clipInfo = clip == null ? "null" : $"{clip.length:0.00}s {clip.samples} samples {clip.loadState}";
            AudioSource src = null;
            if (ok && clip != null)
            {
                src = NextSource();
                src.panStereo = 0f;
                src.PlayOneShot(clip, 0.01f);
            }
            Log?.Info($"[Audio] self-test: source ok={ok}, listeners={listeners.Length} (active {active}), AudioListener.volume={AudioListener.volume:0.00}, pause={AudioListener.pause}, clip={clipInfo}, playing={(src != null && src.isPlaying)}, source volume={(src != null ? src.volume : -1f):0.00}, mute={(src != null && src.mute)}");
        }
        catch (Exception ex) { Log?.Error($"[Audio] self-test failed: {ex}"); }
    }

    private static bool Ensure()
    {
        if (_source != null) return true;
        try
        {
            _host = new GameObject("KingdomAccessAudio");
            UnityEngine.Object.DontDestroyOnLoad(_host);
            _host.hideFlags = HideFlags.HideAndDontSave;
            _pool = new AudioSource[6];
            for (int i = 0; i < _pool.Length; i++)
            {
                var src = _host.AddComponent<AudioSource>();
                src.playOnAwake = false;
                src.spatialBlend = 0f;          // 2D: the stereo position is set by hand
                src.ignoreListenerPause = true;  // also audible while the game is paused
                _pool[i] = src;
            }
            _source = _pool[0];
            _heartbeat = Make("ka_heartbeat", HeartbeatSamples());
            _chime = Make("ka_chime", ChimeSamples());
            return true;
        }
        catch (Exception ex) { Log?.Error($"[Audio] Could not create the audio sources: {ex}"); _source = null; return false; }
    }

    /// <summary>Creates a mono clip from generated samples.</summary>
    public static AudioClip MakeClip(string name, float[] samples) => Make(name, samples);

    /// <summary>Plays any clip (generated or from the game). pan: -1 left to 1 right; volume: 0 to 1.</summary>
    public static void PlayClip(AudioClip clip, float volume, float pan)
    {
        if (!Enabled || clip == null || !Ensure()) return;
        try
        {
            var src = NextSource();
            src.panStereo = Mathf.Clamp(pan, -1f, 1f);
            src.PlayOneShot(clip, Mathf.Clamp01(volume));
        }
        catch { }
    }

    // In Unity 6, AudioClip.SetData only takes a ReadOnlySpan, which this Il2CppInterop version
    // cannot marshal (MissingMethodException): every generated sound stayed silent. The engine's
    // internal call is used directly instead, with the same span wrapper layout (pointer, length).
    private delegate bool SetDataInjected(IntPtr clip, IntPtr spanWrapper, int samplesOffset);
    private static SetDataInjected _setData;

    [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Explicit)]
    private struct SpanWrapper
    {
        [System.Runtime.InteropServices.FieldOffset(0)] public IntPtr Begin;
        [System.Runtime.InteropServices.FieldOffset(8)] public int Length;
    }

    private static unsafe AudioClip Make(string name, float[] samples)
    {
        // AudioClip.Create also passes the clip name as a span: build the clip by hand instead
        // (Construct_Internal, then the CreateUserSound internal call with a char span wrapper).
        var clip = AudioClip.Construct_Internal();
        _createUserSound ??= Il2CppInterop.Runtime.IL2CPP.ResolveICall<CreateUserSoundInjected>("UnityEngine.AudioClip::CreateUserSound_Injected");
        fixed (char* chars = name)
        {
            var nameSpan = new SpanWrapper { Begin = (IntPtr)chars, Length = name.Length };
            _createUserSound(clip.m_CachedPtr, (IntPtr)(&nameSpan), samples.Length, 1, Rate, false);
        }
        _setData ??= Il2CppInterop.Runtime.IL2CPP.ResolveICall<SetDataInjected>("UnityEngine.AudioClip::SetData_Injected");
        fixed (float* begin = samples)
        {
            var wrapper = new SpanWrapper { Begin = (IntPtr)begin, Length = samples.Length };
            _setData(clip.m_CachedPtr, (IntPtr)(&wrapper), 0);
        }
        return clip;
    }

    private delegate void CreateUserSoundInjected(IntPtr self, IntPtr nameSpan, int lengthSamples, int channels, int frequency, bool stream);
    private static CreateUserSoundInjected _createUserSound;

    /// <summary>Heartbeat: two low thumps, the second one softer.</summary>
    private static float[] HeartbeatSamples()
    {
        var s = new float[(int)(Rate * 0.42f)];
        Thump(s, 0f, 0.09f, 1f);
        Thump(s, 0.2f, 0.08f, 0.7f);
        return s;
    }

    private static void Thump(float[] s, float start, float dur, float amp)
    {
        int a = (int)(start * Rate), n = (int)(dur * Rate);
        for (int i = 0; i < n && a + i < s.Length; i++)
        {
            float t = i / (float)Rate;
            float env = Mathf.Exp(-t * 35f) * Mathf.Min(1f, i / 120f);
            float f = 70f - 25f * (i / (float)n); // slight pitch drop, like a heartbeat
            s[a + i] += amp * env * (Mathf.Sin(2f * Mathf.PI * f * t) + 0.3f * Mathf.Sin(4f * Mathf.PI * f * t));
        }
    }

    /// <summary>Chime: two short rising notes.</summary>
    private static float[] ChimeSamples()
    {
        var s = new float[(int)(Rate * 0.22f)];
        Tone(s, 0f, 0.09f, 988f, 0.35f);
        Tone(s, 0.08f, 0.13f, 1319f, 0.3f);
        return s;
    }

    private static void Tone(float[] s, float start, float dur, float freq, float amp)
    {
        int a = (int)(start * Rate), n = (int)(dur * Rate);
        for (int i = 0; i < n && a + i < s.Length; i++)
        {
            float t = i / (float)Rate;
            float env = Mathf.Min(1f, i / 200f) * Mathf.Exp(-t * 18f);
            s[a + i] += amp * env * Mathf.Sin(2f * Mathf.PI * freq * t);
        }
    }

    /// <summary>Plays the heartbeat. pan: -1 left to 1 right; volume: 0 to 1.</summary>
    public static void Heartbeat(float volume, float pan) => Play(_heartbeat, volume, pan, true);

    /// <summary>Plays the "you can pay here" chime.</summary>
    public static void Chime() => Play(_chime, 0.8f, 0f, false);

    private static void Play(AudioClip clip, float volume, float pan, bool isHeartbeat)
    {
        if (!Enabled || !Ensure()) return;
        if (clip == null) clip = isHeartbeat ? _heartbeat : _chime;
        try
        {
            var src = NextSource();
            src.panStereo = Mathf.Clamp(pan, -1f, 1f);
            src.PlayOneShot(clip, Mathf.Clamp01(volume));
        }
        catch { }
    }

    /// <summary>A free source if possible, otherwise the oldest one.</summary>
    private static AudioSource NextSource()
    {
        for (int i = 0; i < _pool.Length; i++)
        {
            var s = _pool[(_next + i) % _pool.Length];
            if (!s.isPlaying) { _next = (_next + i + 1) % _pool.Length; return s; }
        }
        var r = _pool[_next];
        _next = (_next + 1) % _pool.Length;
        r.Stop();
        return r;
    }
}
