using System;
using Il2CppInterop.Runtime.InteropTypes.Arrays;
using UnityEngine;

namespace KingdomAccess.Speech;

/// <summary>
/// Sounds played through the game's own audio engine, with volume and stereo position (unlike
/// the WAV alerts played by Windows). The sounds are generated by the mod: a heartbeat used as a
/// guiding beacon, and a short chime meaning "you can pay here".
/// </summary>
internal static class GameAudio
{
    private const int Rate = 44100;
    private static GameObject _host;
    private static AudioSource _source;
    private static AudioClip _heartbeat, _chime;
    public static bool Enabled = true;

    private static bool Ensure()
    {
        if (_source != null) return true;
        try
        {
            _host = new GameObject("KingdomAccessAudio");
            UnityEngine.Object.DontDestroyOnLoad(_host);
            _host.hideFlags = HideFlags.HideAndDontSave;
            _source = _host.AddComponent<AudioSource>();
            _source.playOnAwake = false;
            _source.spatialBlend = 0f;          // 2D: the stereo position is set by hand
            _source.ignoreListenerPause = true;  // also audible while the game is paused
            _heartbeat = Make("ka_heartbeat", HeartbeatSamples());
            _chime = Make("ka_chime", ChimeSamples());
            return true;
        }
        catch { _source = null; return false; }
    }

    private static AudioClip Make(string name, float[] samples)
    {
        var clip = AudioClip.Create(name, samples.Length, 1, Rate, false);
        clip.SetData(new Il2CppStructArray<float>(samples), 0);
        return clip;
    }

    /// <summary>Heartbeat: two low thumps, the second one softer.</summary>
    private static float[] HeartbeatSamples()
    {
        var s = new float[(int)(Rate * 0.42f)];
        Thump(s, 0f, 0.09f, 1f);
        Thump(s, 0.2f, 0.08f, 0.7f);
        return s;
    }

    private static void Thump(float[] s, float start, float dur, float amp)
    {
        int a = (int)(start * Rate), n = (int)(dur * Rate);
        for (int i = 0; i < n && a + i < s.Length; i++)
        {
            float t = i / (float)Rate;
            float env = Mathf.Exp(-t * 35f) * Mathf.Min(1f, i / 120f);
            float f = 70f - 25f * (i / (float)n); // slight pitch drop, like a heartbeat
            s[a + i] += amp * env * (Mathf.Sin(2f * Mathf.PI * f * t) + 0.3f * Mathf.Sin(4f * Mathf.PI * f * t));
        }
    }

    /// <summary>Chime: two short rising notes.</summary>
    private static float[] ChimeSamples()
    {
        var s = new float[(int)(Rate * 0.22f)];
        Tone(s, 0f, 0.09f, 988f, 0.35f);
        Tone(s, 0.08f, 0.13f, 1319f, 0.3f);
        return s;
    }

    private static void Tone(float[] s, float start, float dur, float freq, float amp)
    {
        int a = (int)(start * Rate), n = (int)(dur * Rate);
        for (int i = 0; i < n && a + i < s.Length; i++)
        {
            float t = i / (float)Rate;
            float env = Mathf.Min(1f, i / 200f) * Mathf.Exp(-t * 18f);
            s[a + i] += amp * env * Mathf.Sin(2f * Mathf.PI * freq * t);
        }
    }

    /// <summary>Plays the heartbeat. pan: -1 left to 1 right; volume: 0 to 1.</summary>
    public static void Heartbeat(float volume, float pan) => Play(_heartbeat, volume, pan, true);

    /// <summary>Plays the "you can pay here" chime.</summary>
    public static void Chime() => Play(_chime, 0.8f, 0f, false);

    private static void Play(AudioClip clip, float volume, float pan, bool isHeartbeat)
    {
        if (!Enabled || !Ensure()) return;
        if (clip == null) clip = isHeartbeat ? _heartbeat : _chime;
        try
        {
            _source.panStereo = Mathf.Clamp(pan, -1f, 1f);
            _source.PlayOneShot(clip, Mathf.Clamp01(volume));
        }
        catch { }
    }
}
